export const feedLabels = {
  createPostPlaceholder: "What's happening?",
  postButton: 'Post',
  feedTitle: 'Your Feed',
  forYouTab: 'For you',
  followingTab: 'Following',
  loadingPosts: 'Loading posts...',
  noPosts: 'No posts yet',
  noPostsSubtitle: 'Follow people to see their posts in your feed',
  followingEmpty: 'Start following to see posts',
  followingEmptySubtitle: 'When you follow people, their posts will show up here.',
  loadMore: 'Load More',
  loading: 'Loading...',
  replyTo: 'Reply to',
  comments: 'Comments',
  replying: 'Replying...',
  reply: 'Reply',
  writeReply: 'Write your reply...',
  addImage: 'Add image',
  selectImageFile: 'Please select an image file',
  youReposted: 'You',
  reposted: 'reposted',
};
